name: ViaRewind
main: com.viaversion.viarewind.BukkitPlugin
authors: [ EnZaXD, Gerrygames, creeper123123321 ]
version: ${version}
description: ${description}
website: https://viaversion.com/rewind
api-version: 1.13
folia-supported: true
load: STARTUP
depend: [ ViaVersion, ViaBackwards ]
