name: ViaRewind
version: ${project.version}
main: de.gerrygames.viarewind.BukkitPlugin
api-version: 1.13
folia-supported: true

authors: [Gerrygames]
website: https://viaversion.com/rewind

load: STARTUP
depend: [ViaVersion]
softdepend: [ViaBackwards]
